In [1]:
import pandas as pd 
import numpy as np 
import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
import mord
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
import pickle

In [2]:
print("start")

output = open("train4.pkl", "rb")
train = pickle.load(output)
train = train.dropna()

y = train["y"]
x = train.drop("y", axis = 1)
print(y.head(10))

start
0     5
1     5
2     1
4     4
5     3
6     3
7     5
8     2
9     5
11    3
Name: y, dtype: int64


In [3]:
x_train, x_val, y_train, y_val = train_test_split(x, y, train_size = 0.75)

# # Import the model we are using
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 100 decision trees
rf = RandomForestClassifier(n_estimators=500)
# Train the model on training data
rf.fit(x_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [4]:
# Use the forest's predict method on the test data
y_pred = rf.predict(x_train)
# Calculate the absolute errors
print("Accuracy:",accuracy_score(y_train, y_pred))
from sklearn.metrics import confusion_matrix
cmatrix = confusion_matrix(y_train, y_pred)
print(cmatrix)

Accuracy: 1.0
[[2307    0    0    0    0]
 [   0 2765    0    0    0]
 [   0    0 4045    0    0]
 [   0    0    0 8185    0]
 [   0    0    0    0 8783]]


In [5]:
y_pred = rf.predict(x_val)
# Calculate the absolute errors
print("Accuracy:",accuracy_score(y_val, y_pred))
from sklearn.metrics import confusion_matrix
cmatrix = confusion_matrix(y_val, y_pred)
print(cmatrix)

Accuracy: 0.5196089706728004
[[ 514   81   23  139   67]
 [ 217  144  114  366  106]
 [  63   48  149  835  188]
 [  24    9   35 1506 1145]
 [   9    1    8  699 2205]]


In [6]:
output = open("randomForestClassifier4.pkl", "wb")
pickle.dump(rf, output)

# model = open("randomForestClassifier1.pkl", "rb")
# rf = pickle.load(model)
# y_pred = rf.predict(x_val)
# confusion_matrix = confusion_matrix(y_val, y_pred)
# print(confusion_matrix)

# print("Accuracy:",accuracy_score(y_val, y_pred))